collector:
  interval: 60s
  timeout: 15s
  include_user_metrics: false
  include_job_inspection_metrics: false
  include_job_sample_histograms: false

pbs:
  binary_dir: /opt/pbs/bin

web:
  telemetry_path: /metrics
